# Generated by Django 4.2.11 on 2026-04-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Identificador único del dispositivo (ej. 1)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej. Sensor Salón)', max_length=100)),
                ('is_sensor', models.BooleanField(default=False, help_text='¿Es un sensor? (Falso implica que es un interruptor o reloj)')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_uid', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la regla', max_length=100)),
                ('operator', models.CharField(choices=[('==', 'Igual a'), ('>', 'Mayor que'), ('<', 'Menor que')], help_text='Operador de comparación', max_length=2)),
                ('condition_value', models.FloatField(help_text='Valor a comparar')),
                ('action_command', models.CharField(help_text='Comando a enviar (ej. ON, OFF)', max_length=50)),
                ('target_device', models.ForeignKey(help_text='Dispositivo sobre el que se realizará la acción', on_delete=django.db.models.deletion.CASCADE, related_name='rules_targeted', to='app.device')),
                ('trigger_device', models.ForeignKey(help_text='Dispositivo que dispara la regla', on_delete=django.db.models.deletion.CASCADE, related_name='rules_triggered', to='app.device')),
            ],
        ),
    ]
