# Generated by Django 5.2.11 on 2026-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rule_time_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_sensor',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('switch', 'Switch'), ('clock', 'Clock')], default='sensor', help_text='Selecciona el tipo de dispositivo', max_length=10),
        ),
    ]
