# Generated by Django 5.2.11 on 2026-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_device_is_sensor_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='clock_increment',
            field=models.IntegerField(blank=True, help_text='Incremento en segundos', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='host',
            field=models.CharField(blank=True, default='localhost', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='interval',
            field=models.FloatField(blank=True, help_text='Intervalo en segundos', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Valor máximo', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Valor mínimo', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(blank=True, default=1883, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='probability',
            field=models.FloatField(blank=True, help_text='Probabilidad de fallo (0.0 a 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='rate',
            field=models.FloatField(blank=True, help_text='Frecuencia (mensajes por segundo)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sensor_increment',
            field=models.IntegerField(blank=True, help_text='Incremento', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='start_time',
            field=models.CharField(blank=True, help_text='Hora de inicio (HH:MM:SS)', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('switch', 'Switch'), ('clock', 'Clock')], default='sensor', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(help_text='Identificador único (ej. 1)', max_length=100, unique=True),
        ),
    ]
