# Generated by Django 5.2.11 on 2026-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_device_clock_increment_device_host_device_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('switch', 'Switch'), ('clock', 'Clock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(help_text='Identificador único', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action_command',
            field=models.CharField(help_text='Comando a enviar (ON, OFF)', max_length=50),
        ),
    ]
